# Generated by Django 2.1.7 on 2019-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190615_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
