# Generated by Django 2.1.7 on 2019-04-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('BIK', models.CharField(max_length=45)),
                ('INN', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField()),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=45)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Clinic')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='inspections',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Patient'),
        ),
    ]
