# Generated by Django 2.1.7 on 2019-06-14 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20190501_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
