# Generated by Django 2.1.7 on 2019-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20190615_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='director',
            field=models.IntegerField(unique=True),
        ),
    ]
