# Generated by Django 2.1.7 on 2019-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_auto_20190615_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
