# Generated by Django 2.1.7 on 2019-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_auto_20190615_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='BIK',
            field=models.CharField(max_length=45, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='INN',
            field=models.CharField(max_length=45, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='contact_address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='director',
            field=models.IntegerField(unique=True, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название клиники'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
