# Generated by Django 2.1.7 on 2019-06-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_auto_20190615_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captures',
            new_name='Capture',
        ),
        migrations.RenameModel(
            old_name='Inspections',
            new_name='Inspection',
        ),
    ]
