# Generated by Django 2.1.7 on 2019-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_auto_20190627_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('bill_data', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('is_payed', models.BooleanField()),
                ('status_description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('bill_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicsTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.IntegerField()),
                ('clinic_id', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('BIK', models.CharField(max_length=255)),
                ('INN', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('bill_date', models.DateField()),
                ('clinic_id', models.IntegerField()),
                ('bill_number', models.IntegerField()),
                ('operation_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('transactions_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('is_enabled', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TariffsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('transactions_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsLeftover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('transactions_left', models.IntegerField()),
            ],
        ),
    ]
